# Generated by Django 4.0.6 on 2023-01-31 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwisko i imię')),
                ('location', models.CharField(max_length=100, verbose_name='miejscowość')),
                ('comments', models.TextField(blank=True, max_length=300, null=True, verbose_name='uwagi')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number', models.CharField(max_length=20, verbose_name='numer pola')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='powierzchnia pola')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='opis pola')),
                ('parcel_number', models.CharField(max_length=30, verbose_name='numer działki')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liming.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pha_crop_type', models.CharField(blank=True, choices=[('GO', 'Grunty orne'), ('UZ', 'Trwałe użytki zielone')], max_length=2, null=True, verbose_name='typ uprawy')),
                ('pha_soil_agronomic_category', models.CharField(blank=True, choices=[('1', '1 - Bardzo lekka'), ('2', '2 - Lekka'), ('3', '3 - Średnia'), ('4', '4 - Ciężka')], max_length=1, null=True, verbose_name='kategoria agronomiczna gleby')),
                ('pha_soil_ph_H2O', models.CharField(blank=True, choices=[('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.5', '4.5'), ('4.6', '4.6'), ('4.7', '4.7'), ('4.8', '4.8'), ('4.9', '4.9'), ('5.0', '5.0'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.8', '5.8'), ('5.9', '5.9'), ('6.0', '6.0'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('6.6', '6.6'), ('6.7', '6.7'), ('6.8', '6.8'), ('6.9', '6.9'), ('7.0', '7.0'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('7.5', '7.5'), ('7.6', '7.6'), ('7.7', '7.7'), ('7.8', '7.8'), ('7.9', '7.9'), ('8.0', '8.0'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('8.4', '8.4'), ('8.5', '8.5'), ('8.6', '8.6'), ('8.7', '8.7'), ('8.8', '8.8'), ('8.9', '8.9'), ('9.0', '9.0')], max_length=3, null=True, verbose_name='odczyn gleby (pHH2O)')),
                ('pha_lider_ca_application_rate_per_hectare', models.FloatField(blank=True, null=True, verbose_name='dawka nawozu Lider Ca (t/ha)')),
                ('pha_lider_ca_application_rate_per_field', models.FloatField(blank=True, null=True, verbose_name='dawka nawozu Lider Ca (t/pole)')),
                ('cn_crop_kind', models.CharField(blank=True, choices=[('PSZ', 'Pszenica'), ('JEC', 'Jęczmień'), ('OWI', 'Owies'), ('ZYT', 'Żyto'), ('RZE', 'Rzepak'), ('KUK', 'Kukurydza kiszonka'), ('KUZ', 'Kukurydza ziarno'), ('UZ', 'Użytki zielone'), ('BOB', 'Bobowate')], max_length=3, null=True, verbose_name='rodzaj uprawy')),
                ('cn_expected_yield', models.CharField(blank=True, choices=[('W', 'Wysoki'), ('S', 'Średni'), ('N', 'Niski')], max_length=1, null=True, verbose_name='spodziewany plon')),
                ('cn_lider_mg_application_rate_per_hectare', models.FloatField(blank=True, null=True, verbose_name='dawka nawozu Lider Mg (t/ha)')),
                ('cn_lider_mg_application_rate_per_field', models.FloatField(blank=True, null=True, verbose_name='dawka nawozu Lider Mg (t/pole)')),
                ('date_of_calculation', models.DateField(blank=True, null=True, verbose_name='data wyliczenia')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liming.farmer', verbose_name='rolnik')),
                ('growing_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liming.growingfield', verbose_name='pole')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('growing_field', 'operator')},
            },
        ),
    ]
