# Generated by Django 4.0.6 on 2023-02-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liming', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmer',
            unique_together={('name', 'location')},
        ),
    ]
