# Generated by Django 4.0.6 on 2023-02-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liming', '0004_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationrate',
            options={'verbose_name': 'Dawka nawozu', 'verbose_name_plural': 'Dawki nawozu'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['name'], 'verbose_name': 'Rolnik', 'verbose_name_plural': 'Rolnicy'},
        ),
        migrations.AlterModelOptions(
            name='growingfield',
            options={'ordering': ['field_number'], 'verbose_name': 'Pole', 'verbose_name_plural': 'Pola'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', 'client'], 'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
