# Generated by Django 4.0.6 on 2023-02-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liming', '0006_alter_applicationrate_options_order_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
